allowBuilds:
  '@nestjs/core': true
  bcrypt: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/common@11.1.23'
  - '@nestjs/core@11.1.23'
  - '@nestjs/microservices@11.1.23'
  - '@nestjs/platform-express@11.1.23'
  - '@nestjs/testing@11.1.23'
  - ts-jest@29.4.11
