# Identificación del proyecto
sonar.projectKey=Reserva-citas
sonar.projectName=Reserva Citas Medicas Backend
sonar.projectVersion=1.0

# Ruta del código
sonar.sources=src

# Lenguaje
sonar.language=ts

# Excluir cosas innecesarias
sonar.exclusions=**/node_modules/**, **/coverage/**, **/*.spec.ts

# Coverage (IMPORTANTE para subir cobertura)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# URL del servidor
sonar.host.url=http://127.0.0.1:9000

sonar.token=TU_TOKEN


