import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDoctorUserFields1780039787708 implements MigrationInterface {
    name = 'AddDoctorUserFields1780039787708'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_appointments_doctor"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_appointments_patient"`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" DROP CONSTRAINT "FK_doctor_exceptions_doctor"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "FK_appointment_history_appointment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_appointment_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_patient_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_doctor_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doctors_active_days"`);
        await queryRunner.query(`DROP INDEX "public"."idx_doctors_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_configs_value"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_doctor_exceptions_doctor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_appointment_history_appointment"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_document_length"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_first_name_length"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_last_name_length"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_phone_length"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_gender"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_patients_email"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "CHK_appointments_status"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_users_email_length"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_users_first_name_length"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_users_last_name_length"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_users_role"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "CHK_doctors_name_length"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "CHK_doctors_specialty_length"`);
        await queryRunner.query(`ALTER TABLE "configs" DROP CONSTRAINT "CHK_configs_key_length"`);
        await queryRunner.query(`ALTER TABLE "configs" DROP CONSTRAINT "CHK_configs_value_json"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_ah_change_type_length"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_ah_previous_status_length"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_ah_new_status_length"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_ah_changed_by_length"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_ah_changed_by_role_length"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "appointment_type"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "must_change_password" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "document" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "doctors_email_key"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "UQ_62069f52ebba471c91de5d59d61" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "UQ_653c27d1b10652eb0c7bbbc4427" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "schedule_start" SET DEFAULT '08:00'`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "schedule_end" SET DEFAULT '18:00'`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "active_days" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" ALTER COLUMN "doctor_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e44a44b3eec38bb354c8425945" ON "appointments"  ("appointment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3330f054416745deaa2cc13070" ON "appointments"  ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4cf26c3f972d014df5c68d503d" ON "appointments"  ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab11f69157b9293c7a8469ce3c" ON "doctors" USING gin ("active_days") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c4f57f6e34c260a25ebf3c27c" ON "configs" USING gin ("value") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d5e948641820eaed2ce89f270" ON "doctor_exceptions"  ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_492bdb7d7fff7082d957ad2757" ON "appointment_history"  ("appointment_id") `);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_117e53ce0580fc1bac520b36b7" CHECK ("email" IS NULL OR "email" ~* '^[^@]+@[^@]+$')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_d8e675d7c06b6489eb44aaca1f" CHECK ("gender" IN ('M', 'F', 'O'))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_d7be258e4e756711be9df0be56" CHECK (LENGTH("phone") <= 20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_83e63cd2c12c498a8581624147" CHECK (LENGTH("last_name") <= 100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_39a128eed427767cb5cee17999" CHECK (LENGTH("first_name") <= 100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_5103c87d8363e974e6c538e723" CHECK (LENGTH("document") <= 20)`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "CHK_7670c952b4fc5f690efddf4658" CHECK ("status" IN ('agendada', 'confirmada', 'completada', 'cancelada'))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_e7e58a5f0a08b056d8687f49a4" CHECK ("role" IN ('admin', 'staff', 'doctor'))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_ec2048cfbd1f1b9b348791664a" CHECK (LENGTH("last_name") <= 100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_16c376c3ac1d77683ead0b1adb" CHECK (LENGTH("first_name") <= 100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_198b9ea03b6ce66450f15333cd" CHECK (LENGTH("email") <= 100)`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "CHK_58f7998f0aeaef51f4aaf9d2e2" CHECK (LENGTH("specialty") <= 100)`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "CHK_b814d245e7b537bdf2cc45593f" CHECK (LENGTH("name") <= 100)`);
        await queryRunner.query(`ALTER TABLE "configs" ADD CONSTRAINT "CHK_4a82ab157259b470fc7b5ac74b" CHECK (jsonb_typeof("value") = 'object')`);
        await queryRunner.query(`ALTER TABLE "configs" ADD CONSTRAINT "CHK_43d942b9295476e89f8e09b571" CHECK (LENGTH("key") <= 100)`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_af3824c58546bda1c0a701a422" CHECK (LENGTH("changed_by_role") <= 30)`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_cf3b1b0dc767417c8c5f90c523" CHECK (LENGTH("changed_by") <= 100)`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_f464ba93889cf7c67173f928d9" CHECK (LENGTH("new_status") <= 20)`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_79338f2bfdf78d5d0b3525eccc" CHECK (LENGTH("previous_status") <= 20)`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_f3711fdf14e9a51bf85c52b45c" CHECK (LENGTH("change_type") <= 30)`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" ADD CONSTRAINT "FK_0d5e948641820eaed2ce89f270b" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "FK_492bdb7d7fff7082d957ad2757a" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "FK_492bdb7d7fff7082d957ad2757a"`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" DROP CONSTRAINT "FK_0d5e948641820eaed2ce89f270b"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_f3711fdf14e9a51bf85c52b45c"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_79338f2bfdf78d5d0b3525eccc"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_f464ba93889cf7c67173f928d9"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_cf3b1b0dc767417c8c5f90c523"`);
        await queryRunner.query(`ALTER TABLE "appointment_history" DROP CONSTRAINT "CHK_af3824c58546bda1c0a701a422"`);
        await queryRunner.query(`ALTER TABLE "configs" DROP CONSTRAINT "CHK_43d942b9295476e89f8e09b571"`);
        await queryRunner.query(`ALTER TABLE "configs" DROP CONSTRAINT "CHK_4a82ab157259b470fc7b5ac74b"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "CHK_b814d245e7b537bdf2cc45593f"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "CHK_58f7998f0aeaef51f4aaf9d2e2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_198b9ea03b6ce66450f15333cd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_16c376c3ac1d77683ead0b1adb"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_ec2048cfbd1f1b9b348791664a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_e7e58a5f0a08b056d8687f49a4"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "CHK_7670c952b4fc5f690efddf4658"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_5103c87d8363e974e6c538e723"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_39a128eed427767cb5cee17999"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_83e63cd2c12c498a8581624147"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_d7be258e4e756711be9df0be56"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_d8e675d7c06b6489eb44aaca1f"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "CHK_117e53ce0580fc1bac520b36b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_492bdb7d7fff7082d957ad2757"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d5e948641820eaed2ce89f270"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c4f57f6e34c260a25ebf3c27c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab11f69157b9293c7a8469ce3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cf26c3f972d014df5c68d503d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3330f054416745deaa2cc13070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e44a44b3eec38bb354c8425945"`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" ALTER COLUMN "doctor_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "active_days" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "schedule_end" SET DEFAULT '18:00:00'`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "schedule_start" SET DEFAULT '08:00:00'`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "UQ_653c27d1b10652eb0c7bbbc4427"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "UQ_62069f52ebba471c91de5d59d61"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "doctors_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "doctors" ALTER COLUMN "document" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "must_change_password" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "appointment_type" character varying(20) DEFAULT 'general'`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_ah_changed_by_role_length" CHECK ((length((changed_by_role)::text) <= 30))`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_ah_changed_by_length" CHECK ((length((changed_by)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_ah_new_status_length" CHECK ((length((new_status)::text) <= 20))`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_ah_previous_status_length" CHECK ((length((previous_status)::text) <= 20))`);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "CHK_ah_change_type_length" CHECK ((length((change_type)::text) <= 30))`);
        await queryRunner.query(`ALTER TABLE "configs" ADD CONSTRAINT "CHK_configs_value_json" CHECK ((jsonb_typeof(value) = 'object'::text))`);
        await queryRunner.query(`ALTER TABLE "configs" ADD CONSTRAINT "CHK_configs_key_length" CHECK ((length((key)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "CHK_doctors_specialty_length" CHECK ((length((specialty)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "CHK_doctors_name_length" CHECK ((length((name)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_users_role" CHECK (((role)::text = ANY ((ARRAY['admin'::character varying, 'staff'::character varying, 'doctor'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_users_last_name_length" CHECK ((length((last_name)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_users_first_name_length" CHECK ((length((first_name)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_users_email_length" CHECK ((length((email)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "CHK_appointments_status" CHECK (((status)::text = ANY ((ARRAY['agendada'::character varying, 'confirmada'::character varying, 'completada'::character varying, 'cancelada'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_email" CHECK (((email IS NULL) OR ((email)::text ~* '^[^@]+@[^@]+$'::text)))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_gender" CHECK (((gender)::text = ANY ((ARRAY['M'::character varying, 'F'::character varying, 'O'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_phone_length" CHECK ((length((phone)::text) <= 20))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_last_name_length" CHECK ((length((last_name)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_first_name_length" CHECK ((length((first_name)::text) <= 100))`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "CHK_patients_document_length" CHECK ((length((document)::text) <= 20))`);
        await queryRunner.query(`CREATE INDEX "IDX_appointment_history_appointment" ON "appointment_history" USING btree ("appointment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_doctor_exceptions_doctor" ON "doctor_exceptions" USING btree ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_configs_value" ON "configs" USING gin ("value") `);
        await queryRunner.query(`CREATE INDEX "idx_doctors_email" ON "doctors" USING btree ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_doctors_active_days" ON "doctors" USING gin ("active_days") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_status" ON "appointments" USING btree ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_doctor_id" ON "appointments" USING btree ("doctor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_patient_id" ON "appointments" USING btree ("patient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_appointments_appointment_date" ON "appointments" USING btree ("appointment_date") `);
        await queryRunner.query(`ALTER TABLE "appointment_history" ADD CONSTRAINT "FK_appointment_history_appointment" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_exceptions" ADD CONSTRAINT "FK_doctor_exceptions_doctor" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_appointments_patient" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_appointments_doctor" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
